module.exports.democrats = ['JoeLieberman', 'RepMikeQuigley', 'BilbrayCA50', 'DrPhilRoe', 'RepJimMatheson', 'GabbyGiffords', 'SenSherrodBrown', 'RepJoeBaca', 'USRepMikeDoyle', 'RepMaxineWaters', 'RepBrianHiggins', 'FrankPallone', 'jahimes', 'SenSanders', 'SenJeffMerkley', 'HarryEMitchell', 'RepHankJohnson', 'GregoryMeeks', 'WhipHoyer', 'SenMarkey', 'cbrangel', 'RepPerlmutter', 'RepSchrader', 'SenArlenSpecter', 'RepSteveIsrael', 'MikeHMichaud', 'LeonardBoswell', 'ArturDavis', 'repbenraylujan', 'mlfudge', 'RepSires', 'SenatorMenendez', 'RepJimMatheson', 'askgeorge', 'MarkWarner', 'MarkUdall']


module.exports.republicans = ['BachusAL06', 'Robert_Aderholt', 'RonPaul', 'JudgeTedPoe', 'SenBobCorker', 'VoteMarsha', 'RepAdamSmith', 'BillCassidy', 'DrPhilRoe', 'DeanHeller', 'RepGoodlatte', 'repdonyoung', 'JackKingston', 'RandyNeugebauer', 'RepMikeRogersAL', 'DrPhilGingrey', 'repgregwalden', 'PatrickMcHenry', 'RepWalterJones', 'johnthune', 'RepGusBilirakis', 'congbillposey', 'RepTrentFranks', 'PeteSessions', 'RepKenMarchant', 'TomRooney', 'GreggHarper', 'ConnieMackIV', 'CynthiaLummis', 'RepBillShuster', 'DarrellIssa', 'JudyBiggert', 'RoyBlunt', 'SenatorBurr', 'SteveAustria', 'VernBuchanan', 'AnderCrenshaw', 'RepMaryFallin', 'RepCliffStearns', 'SenArlenSpecter', 'RepJoeBarton', 'RepKevinBrady', 'SenatorCollins', 'RepLynnJenkins', 'MaryBonoUSA', 'RepMikeCoffman', 'SenJohnMcCain', 'SpeakerRyan', 'zachwamp', 'PaulBrounMD', 'JeffFortenberry', 'JerryMoran', 'LEETERRYNE', 'RepPeteKing', 'MicheleBachmann', 'OrrinHatch', 'Jim_Jordan', 'RepTomPrice', 'SpeakerBoehner', 'ThadMcCotter' ]

module.exports.republican = ['BachusAL06', 'Robert_Aderholt', 'RonPaul', 'JudgeTedPoe', 'SenBobCorker', 'VoteMarsha', 'RepAdamSmith', 'BillCassidy', 'DrPhilRoe', 'DeanHeller', 'RepGoodlatte', 'repdonyoung', 'JackKingston', 'RandyNeugebauer', 'RepMikeRogersAL', 'DrPhilGingrey', 'repgregwalden', 'PatrickMcHenry', 'RepWalterJones', 'johnthune', 'RepGusBilirakis', 'congbillposey', 'RepTrentFranks', 'PeteSessions', 'RepKenMarchant', 'TomRooney', 'GreggHarper', 'ConnieMackIV', 'CynthiaLummis', 'RepBillShuster', 'DarrellIssa', 'JudyBiggert', 'RoyBlunt', 'SenatorBurr', 'SteveAustria', 'VernBuchanan', 'AnderCrenshaw', 'RepMaryFallin', 'RepCliffStearns', 'SenArlenSpecter', 'RepJoeBarton', 'RepKevinBrady', 'SenatorCollins', 'RepLynnJenkins', 'MaryBonoUSA', 'RepMikeCoffman', 'SenJohnMcCain', 'SpeakerRyan', 'zachwamp', 'PaulBrounMD', 'JeffFortenberry', 'JerryMoran', 'LEETERRYNE', 'RepPeteKing', 'MicheleBachmann', 'OrrinHatch', 'Jim_Jordan', 'ohnBoozman', 'RepTomPrice', 'SpeakerBoehner', 'ThadMcCotter' ]


module.exports.religious = ['DalaiLama', 'padrealberto', 'Park51', 'RevJJackson', 'DeepakChopra', 'RickWarren', 'RabbiShmuley', 'thichnhathanh', 'LamaSuryaDas', 'QueenRania', 'BabaRamDass', 'JamesMartinSJ', 'BradHirschfield', 'greenpatriarch', 'EbooPatel', 'jimwallis', 'jdforward', 'Chabad', 'hayimherring', 'jewsforjudaism', 'TheChaviva', 'DigitalJudaism', 'JewishTweets', 'JYuter', 'chiefrabbi', 'RabbiJason', 'imabima', 'Maestrouzy', 'Hadithoftheday', 'mediaiou', 'muslimcouncil', 'BritIslam', 'RamakrishnaQts', 'srimatham', 'narendramodi', 'SriSriSpeaks', 'SwamiDoseDaily', 'HinduismToday', 'swami_sivananda', 'OmTimes', 'BuddhistGeeks', '12stepbuddhist', 'IslamSikhism', 'SikhNet']                                                           

module.exports.atheist = ['AtheistQ', 'DailyAtheist', 'AmericanAtheist', 'Atheism101', 'AntiReligion', 'ThinkAtheist', 'LindaBeatty', 'pinkheretic', 'sherlockmichael', 'Hey_Theist', 'ProAntiTheist', 'antitheistes', 'atheistpro', 'atheist_punk1', 'SkepticNikki', 'SuzzeOsmond', 'DavidMadisonPhD', 'titan511', 'FeedAtheism', 'Human_Town', 'GentleAtheist', 'FeedAtheism', 'CrispySea', 'reasonandlogic', 'JamesSager', 'AlltRightyThen', 'LFaraday', 'zachbatten', 'tarun26atheist', 'factCQ', 'nicolev1978', 'atheistpro', 'iamAtheistGirl', ]

 module.exports.male = ['justinbieber', 'BarackObama', 'jtimberlake', 'Cristiano', 'jimmyfallon', 'BillGates', 'KingJames', 'Drake', 'KevinHart4real', 'BrunoMars', 'NiallOffical', 'onedirection', 'neymarjr', 'wizkhalifa', 'LilTunechi', 'Harry_Styles', 'KAKA', 'ActuallyNPH', 'iamsrk', 'LiamPayne', 'pitbull', 'ConanOBrien', 'zaynmalik', 'chrisbrown', 'davidguetta', 'edsheeran', 'blakeshelton', 'aplusk', 'ricky_martin', 'sachin_rt', 'LeoDiCaprio', 'SnoopDogg'  ]

 module.exports.female = ['katyperry','tayorswift13', 'rihanna', 'TheEllenShow', 'ladygaga', 'britneyspears', 'KimKardashian', 'selenagomez', 'ArianaGrande', 'ddlovato', 'shakira', 'JLo', 'Oprah', 'MileyCyrus', 'Pink', 'Adele', 'aliciakeys', 'EmmaWatson', 'khloekardashian', 'KendallJenner', 'KylieJenner', 'AvrilLavigne', 'NICKIMINAJ', 'deepikapadukone', 'priyankachopra', 'MariahCarey', 'HillaryClinton' ]

